# SYD DAT 7 - Clustering and Trees

##Homework - Due March 27th 2017

* For the following, continue to use the github repository you made for your project
* You don't have to use the same data that you used from the previous homework assignment if
  you have decided to change what your project is about.

### CLUSTERING 
* Identify some attributes where you would expect clustering to be successful.

* Try two or more different clustering algorithms, and experiment with
  different numbers of clusters.

* If the clustering works well, try to give descriptive names for the
  different clusters you have found. If the clustering isn't
  successful, try to hypothesise why your data is some homogenous (and
  try clustering on different attributes).

### DECISION TREES
* Try building decision trees on your data. If you think simplicity
  would be good, try to make it as simple as possible. If you think
  accuracy is more important, use ensembling or any other techniques
  that you have learned.

* Evaluate the success of your model (you can use another model from another
  assigment if this doesn't work well).

In [ ]:
# CLUSTERING 

#1) Identify some attributes where you would expect clustering to be successful:
## age & occupation: younger have more junior type roles and older have more senior roles like lawyer, scientist, dr etc
## movies & genre
## user & rating: is user consistent in rating movies?

In [3]:
# pre-processing
import pandas as pd



In [5]:
ratingsDF = pd.read_table("C:\\datasets\\MovieLens_1mil\\data\\ratings.dat",
                       sep = "::",
                       header = None,
                       names = ['UserID', 'MovieID', 'Rating', 'TimeStamp'],
                       engine = 'python')

In [6]:
ratingsDF.head()
# ratings are 1 to 5 with 5 being the best

UserID  MovieID  Rating  TimeStamp
0       1     1193       5  978300760
1       1      661       3  978302109
2       1      914       3  978301968
3       1     3408       4  978300275
4       1     2355       5  978824291

In [10]:
# just want UserID & Rating
UserID_Rating = ratingsDF[['UserID', 'Rating']]


In [47]:
UserID_Rating.head()

UserID  Rating
0       1       5
1       1       3
2       1       3
3       1       4
4       1       5

In [49]:
UserID_Rating.describe()

UserID        Rating
count  1.000209e+06  1.000209e+06
mean   3.024512e+03  3.581564e+00
std    1.728413e+03  1.117102e+00
min    1.000000e+00  1.000000e+00
25%    1.506000e+03  3.000000e+00
50%    3.070000e+03  4.000000e+00
75%    4.476000e+03  4.000000e+00
max    6.040000e+03  5.000000e+00

In [54]:
UserID_Rating.shape


(1000209, 2)

In [14]:
# needs to be an arry

import numpy

UserID_Rating_array = UserID_Rating.values
UserID_Rating_array

array([[   1,    5],
       [   1,    3],
       [   1,    3],
       ..., 
       [6040,    5],
       [6040,    4],
       [6040,    4]], dtype=int64)

In [15]:
UserID_Rating_array['DESCR']

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [17]:
#2) Try two or more different clustering algorithms, and experiment with different numbers of clusters.
## k means & DB scan

import sklearn.cluster

In [31]:
# kmeans
# clusters = 10 takes over a minute

clusterer = sklearn.cluster.KMeans(n_clusters=5)

In [32]:
cluster_suggestions = clusterer.fit_predict(UserID_Rating_array)
cluster_suggestions
# not sure this output is ok?

array([3, 3, 3, ..., 2, 2, 2])

In [33]:
#cluster validation use silouette 
import sklearn.metrics

In [34]:
sklearn.metrics.silhouette_score(UserID_Rating_array, cluster_suggestions)

MemoryError: 

In [ ]:
# need to fix silhouette_score error

In [35]:
# checking centroids
clusterer.cluster_centers_

# what does this represent?

array([[  3.11561787e+03,   3.60087808e+00],
       [  1.82134065e+03,   3.55782106e+00],
       [  5.45438366e+03,   3.61773947e+00],
       [  6.48342480e+02,   3.56438041e+00],
       [  4.23791329e+03,   3.57072318e+00]])

In [36]:
x = UserID_Rating_array[:,0]
y = UserID_Rating_array[:,1]

In [40]:
colouring = numpy.array(['blue', 'red'])

In [43]:
colour_by_cluster = colouring[cluster_suggestions]
colour_by_cluster

IndexError: index 3 is out of bounds for axis 0 with size 2

In [44]:
#3) If the clustering works well, try to give descriptive names for the different clusters you have found. 
# If the clustering isn't successful, try to hypothesise why your data is some homogenous 
# (and try clustering on different attributes).

# NOTE: K-means is highly scale dependent, and is not suitable for data with widely varying shapes and densities.


# DB scan

In [45]:
#eps = radius

dbscan = sklearn.cluster.DBSCAN(eps=0.5, min_samples=3)

In [46]:
dbscan_suggestions = dbscan.fit_predict(UserID_Rating_array)
dbscan_suggestions


array([    0,     1,     1, ..., 25330, 25327, 25327], dtype=int64)

In [55]:
%matplotlib inline
import matplotlib

matplotlib.pyplot.scatter(x,y, color=colouring[dbscan_suggestions])

IndexError: index 2 is out of bounds for axis 1 with size 2

# DECISION TREES



In [57]:
#1) Try building decision trees on your data. If you think simplicity would be good, try to make it as simple as possible. 
# If you think accuracy is more important, use ensembling or any other techniques that you have learned.

# NOT Complete - go through the following resources: 
    # http://scikit-learn.org/stable/modules/tree.html
    # http://chrisstrelioff.ws/sandbox/2015/06/08/decision_trees_in_python_with_scikit_learn_and_pandas.html
    # http://machinelearningmastery.com/implement-decision-tree-algorithm-scratch-python/

#2) Evaluate the success of your model (you can use another model from another assigment if this doesn't work well).
